### ISSUE TITLE
[tests/e2e] TypeError: 'NoneType' object has no attribute '__getitem__' in pipenv install  

### ISSUE THREAD

**Issue by stephendonner** [mozilla-services/go-bouncer#220]
@davehunt my brain is mush at this point - helpful pointers, if you would?

https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/go-bouncer.adhoc/137/ (and even running locally, for me, against master) yields:

```
02:40:48 Step 4 : COPY requirements.txt /src
02:40:48  ---> Using cache
02:40:48  ---> 5bf630fc453d
02:40:48 Step 5 : RUN pip install pipenv
02:40:48  ---> Using cache
02:40:48  ---> 85735dd5b5ef
02:40:48 Step 6 : RUN pipenv install --system -r requirements.txt --skip-lock --deploy
02:40:49  ---> Running in b738bc7afcb4
02:40:50 Creating a Pipfile for this project…
02:40:50 Traceback (most recent call last):
<snip>
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Fuller output below:

```
02:40:48 Checking out Revision 58acc2ca54237e19299a7e616fb87212746e269f (origin/pyup-update-pytest-3.4.1-to-3.4.2)
02:40:48  > git config core.sparsecheckout # timeout=10
02:40:48  > git checkout -f 58acc2ca54237e19299a7e616fb87212746e269f
02:40:48 Commit message: "Update pytest from 3.4.1 to 3.4.2"
[Pipeline] withEnv
[Pipeline] {
[Pipeline] readFile
[Pipeline] sh
02:40:48 [go-bouncer.adhoc@2] Running shell script
02:40:48 + docker build -t a8cf67e9f83d680ef17c18ffab414241b9ded0e2 -f tests/e2e/Dockerfile tests/e2e
02:40:48 Sending build context to Docker daemon  72.7 kB

02:40:48 Step 1 : FROM python:2.7-alpine
02:40:48  ---> 3e4f5b6dfb77
02:40:48 Step 2 : RUN apk add --update gcc libffi-dev musl-dev openssl-dev python-dev
02:40:48  ---> Using cache
02:40:48  ---> 944e88cd23b8
02:40:48 Step 3 : WORKDIR /src
02:40:48  ---> Using cache
02:40:48  ---> 40ba2f4b58b5
02:40:48 Step 4 : COPY requirements.txt /src
02:40:48  ---> Using cache
02:40:48  ---> 5bf630fc453d
02:40:48 Step 5 : RUN pip install pipenv
02:40:48  ---> Using cache
02:40:48  ---> 85735dd5b5ef
02:40:48 Step 6 : RUN pipenv install --system -r requirements.txt --skip-lock --deploy
02:40:49  ---> Running in b738bc7afcb4
02:40:50 Creating a Pipfile for this project…
02:40:50 Traceback (most recent call last):
02:40:50   File "/usr/local/bin/pipenv", line 11, in <module>
02:40:50     sys.exit(cli())
02:40:50   File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
02:40:50     return self.main(*args, **kwargs)
02:40:50   File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
02:40:50     rv = self.invoke(ctx)
02:40:50   File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
02:40:50     return _process_result(sub_ctx.command.invoke(sub_ctx))
02:40:50   File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
02:40:50     return ctx.invoke(self.callback, **ctx.params)
02:40:50   File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
02:40:50     return callback(*args, **kwargs)
02:40:50   File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 197, in install
02:40:50     selective_upgrade=selective_upgrade
02:40:50   File "/usr/local/lib/python2.7/site-packages/pipenv/core.py", line 1722, in do_install
02:40:50     ensure_project(three=three, python=python, system=system, warn=True, deploy=deploy, skip_requirements=skip_requirements)
02:40:50   File "/usr/local/lib/python2.7/site-packages/pipenv/core.py", line 653, in ensure_project
02:40:50     ensure_pipfile(validate=validate, skip_requirements=skip_requirements)
02:40:50   File "/usr/local/lib/python2.7/site-packages/pipenv/core.py", line 343, in ensure_pipfile
02:40:50     project.create_pipfile(python=python)
02:40:50   File "/usr/local/lib/python2.7/site-packages/pipenv/project.py", line 435, in create_pipfile
02:40:50     data[u'requires'] = {'python_version': python_version(self.which('python'))[:len('2.7')]}
02:40:50 TypeError: 'NoneType' object has no attribute '__getitem__'
02:40:50 The command '/bin/sh -c pipenv install --system -r requirements.txt --skip-lock --deploy' returned a non-zero code: 1
```

**Comment by davehunt** [comment]
For other repos we've migrated the requirements.txt to Pipfile, perhaps we should do that here?

**Comment by stephendonner** [comment]
@davehunt yes, it's a good idea, and one I've been wanting to do.

I'll take a crack at this in an upcoming PR, now that we know we don't (yet) want the full Pipfile.lock workflow, due to @pyup-bot integration.

**Comment by stephendonner** [comment]
Fixed; done in https://github.com/mozilla-services/go-bouncer/pull/223 - closing this out.
